# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjetNewChauffe.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(747, 513)
        Dialog.setAutoFillBackground(True)
        Dialog.setStyleSheet("")
        self.label_T_ext = QtWidgets.QLabel(Dialog)
        self.label_T_ext.setGeometry(QtCore.QRect(330, 490, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_T_ext.setFont(font)
        self.label_T_ext.setObjectName("label_T_ext")
        self.label_T_salon = QtWidgets.QLabel(Dialog)
        self.label_T_salon.setGeometry(QtCore.QRect(320, 461, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_T_salon.setFont(font)
        self.label_T_salon.setStyleSheet("")
        self.label_T_salon.setTextFormat(QtCore.Qt.AutoText)
        self.label_T_salon.setScaledContents(True)
        self.label_T_salon.setObjectName("label_T_salon")
        self.label_synoptique = QtWidgets.QLabel(Dialog)
        self.label_synoptique.setGeometry(QtCore.QRect(0, 0, 747, 516))
        self.label_synoptique.setStyleSheet("background-image: url(:/images/cuve.jpeg);\n"
"\n"
"")
        self.label_synoptique.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_synoptique.setLineWidth(1)
        self.label_synoptique.setText("")
        self.label_synoptique.setObjectName("label_synoptique")
        self.display_T_Salon = QtWidgets.QLabel(Dialog)
        self.display_T_Salon.setGeometry(QtCore.QRect(450, 458, 51, 21))
        self.display_T_Salon.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_T_Salon.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_T_Salon.setAlignment(QtCore.Qt.AlignCenter)
        self.display_T_Salon.setObjectName("display_T_Salon")
        self.display_T_ext = QtWidgets.QLabel(Dialog)
        self.display_T_ext.setGeometry(QtCore.QRect(450, 488, 51, 21))
        self.display_T_ext.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_T_ext.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_T_ext.setAlignment(QtCore.Qt.AlignCenter)
        self.display_T_ext.setObjectName("display_T_ext")
        self.display_T_pan_sol = QtWidgets.QLabel(Dialog)
        self.display_T_pan_sol.setGeometry(QtCore.QRect(650, 73, 51, 21))
        self.display_T_pan_sol.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_T_pan_sol.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_T_pan_sol.setAlignment(QtCore.Qt.AlignCenter)
        self.display_T_pan_sol.setObjectName("display_T_pan_sol")
        self.display_T_cuve_h = QtWidgets.QLabel(Dialog)
        self.display_T_cuve_h.setGeometry(QtCore.QRect(390, 47, 51, 21))
        self.display_T_cuve_h.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_T_cuve_h.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_T_cuve_h.setAlignment(QtCore.Qt.AlignCenter)
        self.display_T_cuve_h.setObjectName("display_T_cuve_h")
        self.display_T_cuve_m = QtWidgets.QLabel(Dialog)
        self.display_T_cuve_m.setGeometry(QtCore.QRect(390, 210, 51, 21))
        self.display_T_cuve_m.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_T_cuve_m.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_T_cuve_m.setAlignment(QtCore.Qt.AlignCenter)
        self.display_T_cuve_m.setObjectName("display_T_cuve_m")
        self.display_T_cuve_b = QtWidgets.QLabel(Dialog)
        self.display_T_cuve_b.setGeometry(QtCore.QRect(390, 423, 51, 21))
        self.display_T_cuve_b.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_T_cuve_b.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_T_cuve_b.setAlignment(QtCore.Qt.AlignCenter)
        self.display_T_cuve_b.setObjectName("display_T_cuve_b")
        self.display_T_v3v = QtWidgets.QLabel(Dialog)
        self.display_T_v3v.setGeometry(QtCore.QRect(190, 50, 51, 21))
        self.display_T_v3v.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_T_v3v.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_T_v3v.setAlignment(QtCore.Qt.AlignCenter)
        self.display_T_v3v.setObjectName("display_T_v3v")
        self.display_T_ret_panel = QtWidgets.QLabel(Dialog)
        self.display_T_ret_panel.setGeometry(QtCore.QRect(570, 408, 51, 21))
        self.display_T_ret_panel.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_T_ret_panel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_T_ret_panel.setAlignment(QtCore.Qt.AlignCenter)
        self.display_T_ret_panel.setObjectName("display_T_ret_panel")
        self.display_T_dep_panel = QtWidgets.QLabel(Dialog)
        self.display_T_dep_panel.setGeometry(QtCore.QRect(510, 345, 51, 21))
        self.display_T_dep_panel.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_T_dep_panel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_T_dep_panel.setAlignment(QtCore.Qt.AlignCenter)
        self.display_T_dep_panel.setObjectName("display_T_dep_panel")
        self.progressBar_Pos_v3v = QtWidgets.QProgressBar(Dialog)
        self.progressBar_Pos_v3v.setGeometry(QtCore.QRect(225, 9, 118, 20))
        self.progressBar_Pos_v3v.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"color: rgb(255, 0, 0);")
        self.progressBar_Pos_v3v.setProperty("value", 24)
        self.progressBar_Pos_v3v.setObjectName("progressBar_Pos_v3v")
        self.display_P_solaire = QtWidgets.QLabel(Dialog)
        self.display_P_solaire.setGeometry(QtCore.QRect(650, 240, 51, 21))
        self.display_P_solaire.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_P_solaire.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_P_solaire.setAlignment(QtCore.Qt.AlignCenter)
        self.display_P_solaire.setObjectName("display_P_solaire")
        self.display_E_solaire = QtWidgets.QLabel(Dialog)
        self.display_E_solaire.setGeometry(QtCore.QRect(640, 300, 71, 21))
        self.display_E_solaire.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_E_solaire.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_E_solaire.setAlignment(QtCore.Qt.AlignCenter)
        self.display_E_solaire.setObjectName("display_E_solaire")
        self.display_E_chauffage = QtWidgets.QLabel(Dialog)
        self.display_E_chauffage.setGeometry(QtCore.QRect(190, 270, 71, 21))
        self.display_E_chauffage.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(209, 213, 231);")
        self.display_E_chauffage.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.display_E_chauffage.setAlignment(QtCore.Qt.AlignCenter)
        self.display_E_chauffage.setObjectName("display_E_chauffage")
        self.Led_Pompe_Chauffage = QtWidgets.QLabel(Dialog)
        self.Led_Pompe_Chauffage.setGeometry(QtCore.QRect(220, 426, 15, 15))
        self.Led_Pompe_Chauffage.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Led_Pompe_Chauffage.setFrameShape(QtWidgets.QFrame.Box)
        self.Led_Pompe_Chauffage.setText("")
        self.Led_Pompe_Chauffage.setObjectName("Led_Pompe_Chauffage")
        self.Led_Pompe_Solaire = QtWidgets.QLabel(Dialog)
        self.Led_Pompe_Solaire.setGeometry(QtCore.QRect(535, 412, 15, 15))
        self.Led_Pompe_Solaire.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Led_Pompe_Solaire.setFrameShape(QtWidgets.QFrame.Box)
        self.Led_Pompe_Solaire.setText("")
        self.Led_Pompe_Solaire.setObjectName("Led_Pompe_Solaire")
        self.Led_Pompe_Chauffage_2 = QtWidgets.QLabel(Dialog)
        self.Led_Pompe_Chauffage_2.setGeometry(QtCore.QRect(288, 262, 15, 15))
        self.Led_Pompe_Chauffage_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Led_Pompe_Chauffage_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Led_Pompe_Chauffage_2.setText("")
        self.Led_Pompe_Chauffage_2.setObjectName("Led_Pompe_Chauffage_2")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 447, 181, 62))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_Cde_Chauffage = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Cde_Chauffage.setGeometry(QtCore.QRect(10, 33, 101, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Cde_Chauffage.setFont(font)
        self.pushButton_Cde_Chauffage.setObjectName("pushButton_Cde_Chauffage")
        self.Edit_Consigne_T = QtWidgets.QLineEdit(self.groupBox)
        self.Edit_Consigne_T.setGeometry(QtCore.QRect(120, 17, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Edit_Consigne_T.setFont(font)
        self.Edit_Consigne_T.setStyleSheet("background-color: rgb(239, 190, 255);")
        self.Edit_Consigne_T.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Edit_Consigne_T.setObjectName("Edit_Consigne_T")
        self.label_Consigne = QtWidgets.QLabel(self.groupBox)
        self.label_Consigne.setGeometry(QtCore.QRect(10, 15, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_Consigne.setFont(font)
        self.label_Consigne.setStyleSheet("")
        self.label_Consigne.setTextFormat(QtCore.Qt.AutoText)
        self.label_Consigne.setScaledContents(True)
        self.label_Consigne.setObjectName("label_Consigne")
        self.label_synoptique.raise_()
        self.label_T_ext.raise_()
        self.label_T_salon.raise_()
        self.display_T_Salon.raise_()
        self.display_T_ext.raise_()
        self.display_T_pan_sol.raise_()
        self.display_T_cuve_h.raise_()
        self.display_T_cuve_m.raise_()
        self.display_T_cuve_b.raise_()
        self.display_T_v3v.raise_()
        self.display_T_ret_panel.raise_()
        self.display_T_dep_panel.raise_()
        self.progressBar_Pos_v3v.raise_()
        self.display_P_solaire.raise_()
        self.display_E_solaire.raise_()
        self.display_E_chauffage.raise_()
        self.Led_Pompe_Chauffage.raise_()
        self.Led_Pompe_Solaire.raise_()
        self.Led_Pompe_Chauffage_2.raise_()
        self.groupBox.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_T_ext.setText(_translate("Dialog", "Température ext.  :"))
        self.label_T_salon.setText(_translate("Dialog", "Température salon  :"))
        self.display_T_Salon.setText(_translate("Dialog", "xx.x°C"))
        self.display_T_ext.setText(_translate("Dialog", "xx.x°C"))
        self.display_T_pan_sol.setText(_translate("Dialog", "xx.x°C"))
        self.display_T_cuve_h.setText(_translate("Dialog", "xx.x°C"))
        self.display_T_cuve_m.setText(_translate("Dialog", "xx.x°C"))
        self.display_T_cuve_b.setText(_translate("Dialog", "xx.x°C"))
        self.display_T_v3v.setText(_translate("Dialog", "xx.x°C"))
        self.display_T_ret_panel.setText(_translate("Dialog", "xx.x°C"))
        self.display_T_dep_panel.setText(_translate("Dialog", "xx.x°C"))
        self.display_P_solaire.setText(_translate("Dialog", "xx.x kW"))
        self.display_E_solaire.setText(_translate("Dialog", "xx.x kWh/J"))
        self.display_E_chauffage.setText(_translate("Dialog", "xx.x kWh/J"))
        self.groupBox.setTitle(_translate("Dialog", "Commandes Chauffage"))
        self.pushButton_Cde_Chauffage.setText(_translate("Dialog", "MARCHE"))
        self.Edit_Consigne_T.setText(_translate("Dialog", "19,5"))
        self.label_Consigne.setText(_translate("Dialog", "Consigne salon  :"))

import RessourceFile_rc
